import { withHash } from '../util/color'
import type { Generator } from '../types'

const generator: Generator = {
  id: 'alacritty',
  dir: 'alacritty',
  ext: 'toml',
  filename: (palette) => palette.slug,
  render(palette) {
    const h = withHash
    const a = palette.ansi

    return [
      `# ${palette.name} — generated by clowk-terminal`,
      '[colors.primary]',
      `background = "${h(palette.background)}"`,
      `foreground = "${h(palette.foreground)}"`,
      '',
      '[colors.cursor]',
      `cursor = "${h(palette.cursor)}"`,
      `text = "${h(palette.cursorText)}"`,
      '',
      '[colors.selection]',
      `background = "${h(palette.selectionBackground)}"`,
      `text = "${h(palette.selectionForeground)}"`,
      '',
      '[colors.normal]',
      `black = "${h(a.black)}"`,
      `red = "${h(a.red)}"`,
      `green = "${h(a.green)}"`,
      `yellow = "${h(a.yellow)}"`,
      `blue = "${h(a.blue)}"`,
      `magenta = "${h(a.magenta)}"`,
      `cyan = "${h(a.cyan)}"`,
      `white = "${h(a.white)}"`,
      '',
      '[colors.bright]',
      `black = "${h(a.brightBlack)}"`,
      `red = "${h(a.brightRed)}"`,
      `green = "${h(a.brightGreen)}"`,
      `yellow = "${h(a.brightYellow)}"`,
      `blue = "${h(a.brightBlue)}"`,
      `magenta = "${h(a.brightMagenta)}"`,
      `cyan = "${h(a.brightCyan)}"`,
      `white = "${h(a.brightWhite)}"`,
      '',
    ].join('\n')
  },
}

export default generator
