import { withHash } from '../util/color'
import type { Generator } from '../types'

const generator: Generator = {
  id: 'ghostty',
  dir: 'ghostty',
  ext: '',
  filename: (palette) => palette.slug,
  render(palette) {
    const lines = [`# ${palette.name} — generated by clowk-terminal`]

    palette.ansi16.forEach((color, index) => {
      lines.push(`palette = ${index}=${withHash(color)}`)
    })

    lines.push(`background = ${withHash(palette.background)}`)
    lines.push(`foreground = ${withHash(palette.foreground)}`)
    lines.push(`cursor-color = ${withHash(palette.cursor)}`)
    lines.push(`cursor-text = ${withHash(palette.cursorText)}`)
    lines.push(`selection-background = ${withHash(palette.selectionBackground)}`)
    lines.push(`selection-foreground = ${withHash(palette.selectionForeground)}`)

    return `${lines.join('\n')}\n`
  },
}

export default generator
