import { withHash } from '../util/color'
import type { Generator } from '../types'

const generator: Generator = {
  id: 'kitty',
  dir: 'kitty',
  ext: 'conf',
  filename: (palette) => palette.slug,
  render(palette) {
    const lines = [
      `# ${palette.name} — generated by clowk-terminal`,
      `background ${withHash(palette.background)}`,
      `foreground ${withHash(palette.foreground)}`,
      `cursor ${withHash(palette.cursor)}`,
      `cursor_text_color ${withHash(palette.cursorText)}`,
      `selection_background ${withHash(palette.selectionBackground)}`,
      `selection_foreground ${withHash(palette.selectionForeground)}`,
      '',
    ]

    palette.ansi16.forEach((color, index) => {
      lines.push(`color${index} ${withHash(color)}`)
    })

    return `${lines.join('\n')}\n`
  },
}

export default generator
