import { withHash } from '../util/color'
import type { Generator } from '../types'

const generator: Generator = {
  id: 'wezterm',
  dir: 'wezterm',
  ext: 'toml',
  filename: (palette) => palette.slug,
  render(palette) {
    const ansi = palette.ansi16.slice(0, 8).map((c) => `"${withHash(c)}"`).join(', ')
    const brights = palette.ansi16.slice(8).map((c) => `"${withHash(c)}"`).join(', ')

    return [
      `# ${palette.name} — generated by clowk-terminal`,
      '[colors]',
      `foreground = "${withHash(palette.foreground)}"`,
      `background = "${withHash(palette.background)}"`,
      `cursor_bg = "${withHash(palette.cursor)}"`,
      `cursor_fg = "${withHash(palette.cursorText)}"`,
      `cursor_border = "${withHash(palette.cursor)}"`,
      `selection_bg = "${withHash(palette.selectionBackground)}"`,
      `selection_fg = "${withHash(palette.selectionForeground)}"`,
      `ansi = [${ansi}]`,
      `brights = [${brights}]`,
      '',
      '[metadata]',
      `name = "${palette.name}"`,
      '',
    ].join('\n')
  },
}

export default generator
